In [6]:

def SQLRuns(tgt,kin,suf):


    ##########################################
    H3  = ["Tritium" ,"T", "T3", "H3" ]
    D2  = ["Deuterium","D2", "D", "H2" ]
    H   = ["Hydrogen","H1", "H" ]
    He3 = ["Helium-3","Helium","He3"]
    if tgt in H3 :
         TGT = H3[0]
    if tgt in D2 :
         TGT = D2[0]
    if tgt in H :
         TGT = H[0]
    if tgt in He3 :
         TGT = He3[0]

    tgt=TGT
    #########################################        
    if suf == 'all':
        suf='%'
    if suf != '%':
        suf = suf + '%'
    #############
    import mysql.connector
    db_user= 'triton-user'
    db_pswd= '3He3Hdata'
    db_name= 'triton-work'
    db_host= 'halladb'
    cnx = mysql.connector.connect(user=db_user,host=db_host,database=db_name, password=db_pswd)
    cursor = cnx.cursor(buffered=True)
    query1 = 'select run_number from MARATHONrunlist where (Kinematic like "{}/_{}" ESCAPE "/" ) and target="{}" order by run_number asc'.format(kin,suf,tgt)

    print(query1)

    query = 'select run_number from MARATHONrunlist where Kinematic = "{}" and target="{}" order by run_number asc'.format(kin,kin,tgt)
    cursor.execute(query1)
    results= cursor.fetchall()
    rl={}
    for i,row in enumerate(results):
        rl[i]=(row[0])
    return rl
    ####################

In [8]:
SQLRuns("He3",'15','1')

select run_number from MARATHONrunlist where (Kinematic like "15/_1%" ESCAPE "/" ) and target="Helium-3" order by run_number asc

{0: 1841,
 1: 1842,
 2: 1843,
 3: 1844,
 4: 1845,
 5: 1846,
 6: 1847,
 7: 1849,
 8: 1850,
 9: 1851,
 10: 1857,
 11: 1868,
 12: 1869,
 13: 1870,
 14: 1871,
 15: 1872,
 16: 1874,
 17: 1875,
 18: 1876,
 19: 1896,
 20: 1897,
 21: 1898,
 22: 1899,
 23: 1900,
 24: 1917,
 25: 1926,
 26: 1927,
 27: 1928,
 28: 1929,
 29: 1930,
 30: 1931,
 31: 1938,
 32: 1939,
 33: 1941,
 34: 1942,
 35: 1943,
 36: 1944,
 37: 1955,
 38: 1957,
 39: 1958,
 40: 1960,
 41: 1961,
 42: 1962,
 43: 1983,
 44: 1984,
 45: 1985,
 46: 1986,
 47: 1987,
 48: 1995,
 49: 1996,
 50: 1997,
 51: 1998,
 52: 1999,
 53: 2000,
 54: 2011,
 55: 2012,
 56: 2013,
 57: 2014,
 58: 2015,
 59: 2033,
 60: 2034,
 61: 2035,
 62: 2045,
 63: 2046,
 64: 2054,
 65: 2055,
 66: 2058,
 67: 2059,
 68: 2060,
 69: 2061,
 70: 2069,
 71: 2070,
 72: 2071,
 73: 2072,
 74: 2073,
 75: 2083,
 76: 2084,
 77: 2085,
 78: 2086,
 79: 2087,
 80: 2097,
 81: 2098,
 82: 2099,
 83: 2100,
 84: 2101,
 85: 2116,
 86: 2117,
 87: 2118,
 88: 2119,
 89: 2120,
 90: 2129,
 91: 2130,
 92: 2131,
 93: 2132,
 94: 2133,
 95: 2141,
 96: 2142,
 97: 2143,
 98: 2144,
 99: 2145,
 100: 2152,
 101: 2153,
 102: 2154,
 103: 2155,
 104: 2156,
 105: 2164,
 106: 2165,
 107: 2166,
 108: 2167,
 109: 2168,
 110: 2169,
 111: 2181,
 112: 2182,
 113: 2183,
 114: 2184,
 115: 2185,
 116: 2186,
 117: 2193,
 118: 2194,
 119: 2195,
 120: 2196,
 121: 2198,
 122: 2206,
 123: 2207,
 124: 2208,
 125: 2209,
 126: 2210,
 127: 2220,
 128: 2221,
 129: 2222,
 130: 2223,
 131: 2224,
 132: 2225,
 133: 2233,
 134: 2234,
 135: 2235,
 136: 2236,
 137: 2237,
 138: 2255,
 139: 2256,
 140: 2257,
 141: 2258,
 142: 2259,
 143: 2260,
 144: 2268,
 145: 2269,
 146: 2270,
 147: 2272,
 148: 2277,
 149: 2278,
 150: 2279,
 151: 2280,
 152: 2281}